# Generated by Django 4.2.11 on 2024-04-27 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0002_invoice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="cost_center",
            new_name="cost_center_code",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="type_of_cost",
            new_name="cost_code",
        ),
    ]
